formatter: markdown

content : |-
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Resources }}
  ## Usage
   ```hcl
  {{ include "../../examples/vnet_two_way_peering.tf" }}
   ```
  {{ .Outputs }}